version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      FLASK_APP: server.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_ENV: production
    volumes:
      - ./backend:/usr/src/app
    networks:
      - myapp-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - myapp-network

networks:
  myapp-network:
