name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Run tests
      run: |
        cd backend
        pytest

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build and push Docker images
      run: |
        docker build -t myapp-backend:latest ./backend
        docker build -t myapp-frontend:latest ./frontend
        # Push images to a Docker registry (e.g., Docker Hub, GitHub Packages)

    - name: Deploy to server
      run: |
        # Add your deployment commands here (e.g., SSH into server, pull images, restart services)
        echo "Deploying to server..."
